Added team member
sebdraven/esiea-secure-edition.github.io pull request #11
Opened 2024-04-30 17:57 UTC by AnnaOquidam

2024-04-30 18:32 UTC, SuijoART requested changes
ajout de la fonctionnalité de responsive

2024-04-30 18:38 UTC, SuijoART submitted a review, later dismissed
alignement des items

2024-04-30 18:45 UTC, SuijoART requested changes
alignement des items

2024-04-30 18:50 UTC, ghost requested changes
centrage du tableau

2024-05-02 09:13 UTC, sebdraven approved these changes

2024-05-02 09:13 UTC, sebdraven approved these changes

2024-05-02 09:14 UTC, sebdraven approved these changes

2024-05-02 09:19 UTC, SuijoART approved these changes

2024-05-02 09:20 UTC, merged